# /boot/refind_linux.conf
# REFInd configuration file for boot options

"Boot with default options"  	"root=LABEL=RootArchSSD rw add_efi_memmap initrd=boot\intel-ucode.img initrd=boot\initramfs-%v.img nvidia-drm.modeset=1"
"Boot with fallback initramfs"  "root=LABEL=RootArchSSD rw add_efi_memmap initrd=boot\intel-ucode.img initrd=boot\initramfs-%v-fallback.img nvidia-drm.modeset=1"
"Boot to terminal"  		"root=LABEL=RootArchSSD rw add_efi_memmap initrd=boot\intel-ucode.img initrd=boot\initramfs-%v.img systemd.unit=multi-user.target"
